apiVersion: v1
kind: ConfigMap
metadata:
  name: node-script
  namespace: kube-system
data:
  entrypoint.sh: |-
    #!/bin/sh
    journalctl -u portworx*
    touch /ready
    sleep 1d
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node
  namespace: kube-system
  labels:
    name: node
spec:
  selector:
    matchLabels:
      name: node
  minReadySeconds: 0
  template:
    metadata:
      labels:
        name: node
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: px/enabled
                operator: NotIn
                values:
                - "false"
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
      terminationGracePeriodSeconds: 0
      volumes:
      - name: node-script
        configMap:
          defaultMode: 0700
          name: node-script
      - name: run-log
        hostPath:
          path: /run/log
          type: Directory
      containers:
        - name: node
          image: centos:7
          command:
          - /entrypoint.sh
          readinessProbe:
            exec:
              command:
              - cat
              - /ready
          volumeMounts:
          - name: node-script
            mountPath: /entrypoint.sh
            readOnly: true
            subPath: entrypoint.sh
          - name: run-log
            mountPath: /run/log
          env:
            - name: NODES
              valueFrom:
                configMapKeyRef:
                  name: loggetter-config
                  key: nodes
